# @package _global_

model:
  balancing: mine-shuffle
  br_act: true
  br_size: 32
  ema_y: true
  hiddens_D_net:
  - 16
  hiddens_G_x:
  - 16
  hiddens_G_y:
  - 16
  init: 0.001
  recursive: true
  transpose: true
  transpose_size: 64
  
exp:
  batch_size: 128
  beta: 0.999
  dropout: 0.1
  epochs: 500
  lambda_D: 0.01
  lambda_X: 0.1
  lr: 0.001
  lr_D: 0.0001
  patience: 500
  update_lambda_D: true
  weight_decay: 0.0001
  weight_decay_D: 0
