# @package _global_
model:
  balancing: mine-shuffle
  br_act: true
  br_size: 16
  ema_y: true
  hiddens_D_net:
  - 16
  hiddens_G_x:
  - 16
  hiddens_G_y:
  - 32
  init: 0.001
  recursive: true
  transpose: true
  transpose_size: 64
  hidden_size: 16
  num_layers: 1
  hidden_size_x: 16
  num_layers_x: 1
  hidden_size_y: 16

exp:
  batch_size: 64
  beta: 0.999
  dropout: 0.1
  epochs: 500
  lambda_D: 0.01
  lambda_X: 0.05
  lr: 0.01
  lr_D: 0.0002
  patience: 500
  update_lambda_D: true
  weight_decay: 5.0e-05
  weight_decay_D: 0