# @package _global_
model:
  # name: ${model.subname}_br_${model.first_net}_${model.second_net}_recursive=${model.recursive}
  name: ACTIN
  subname: gan
  _target_: src.models.causal_gan_br_model.CausalGanBrModel
  transpose: True
  transpose_size: 16
  first_net: tcn
  second_net: tcn
  recursive: True
  num_channels_hidden: 
    - 12
    - 12
    - 12
  br_size: 12
  br_act: True
  num_channels_hidden_y: 
    - 12
    - 12
  hiddens_G_y: 
    - 32
  hiddens_D_net:
    - 16
  kernel_size: 3
  kernel_size_y: 3
  num_blocks: 2
  ema_y: False
  balancing: mine-shuffle
  init: 0.001
  shffule_mode: all

exp:
  seed: 10
  batch_size: 128
  dropout: 0.1
  sch_patience: 500
  sch_patience_D: 500
  cooldown: 10
  patience: 500
  factor: 0.5
  epochs: 150
  lr: 2.e-3
  lr_D: 1.e-4
  weight_decay: 0
  weight_decay_D: 0
  update_lambda_D: True
  lambda_D: 0.01
  lambda_X: 0.1
  lambda_Y: 1
  loss_type_X: l2
  load_best: True
  val: True
