# @package _global_
model:
  name: ACTIN
  subname: gan
  _target_: src.models.causal_gan_br_model.CausalGanBrModel
  transpose: True
  transpose_size: 16
  first_net: tcn
  second_net: tcn
  recursive: True
  num_channels_hidden: 
    - 16
  br_size: 16
  br_act: True
  num_channels_hidden_y: 
    - 4
    - 4
  num_channels_hidden_x: 
    - 4
    - 4
  hiddens_G_y: 
    - 16
  hiddens_G_x:
    - 16
  hiddens_D_net:
    - 16
  kernel_size: 3
  kernel_size_y: 3
  kernel_size_x: 3
  num_blocks: 2
  ema_y: False
  balancing: mine-shuffle
  init: 0.001
  shffule_mode: all

exp:
  seed: 10
  batch_size: 128
  dropout: 0.
  sch_patience: 500
  sch_patience_D: 500
  cooldown: 10
  patience: 15
  factor: 0.8
  epochs: 300
  lr: 1.e-3
  lr_D: 1.e-4
  weight_decay: 1.e-5
  weight_decay_D: 1.e-5
  gpus: 1
  unscale_rmse: False
  percentage_rmse: False
  weights_ema: True
  lambda_D: 0.01
  lambda_X: 0.1
  lambda_Y: 1
  beta: 0.99
  raw_data_dir: data/raw/sim/
  processed_data_dir: data/processed/sim/
  clear_tf: True
  loss_type_X: l2
  load_best: True
  val: True
  update_lambda_D: True
